"""Constraint-aware inference, repair, fallback, and final selection."""

from .baselines import (
    GreedyLocalResult,
    LatencyAwareHeuristicCandidate,
    LatencyAwareHeuristicResult,
    LocalSearchConfig,
    LocalSearchResult,
    construct_latency_aware_heuristic_candidates,
    construct_latency_aware_heuristic_placement,
    construct_greedy_local_placement,
    run_local_search,
    solve_greedy_local,
    solve_latency_aware_heuristic,
    solve_local_search,
    solve_milp_time_limit,
)
from .fallback import (
    ConstructiveFallbackConfig,
    ConstructiveFallbackResult,
    construct_feasible_placement,
)
from .diagnostics import TrajectoryDiagnosticConfig, diagnose_reverse_trajectory
from .repair import (
    RepairConfig,
    RepairMove,
    RepairResult,
    ViolationScore,
    repair_placement,
    violation_score,
)
from .recovery import (
    ProposalRecoveryConfig,
    ProposalRecoveryResult,
    recover_from_proposal,
)
from .solve import (
    InferenceConfig,
    SolveResult,
    TrajectoryCandidateSet,
    TrajectoryProposalBatch,
    build_trajectory_candidate_set,
    sample_direct_proposals,
    sample_random_proposals,
    sample_reverse_proposals,
    sample_reverse_trajectory_proposals,
    solve_fallback_only,
    solve_from_proposals,
    solve_with_direct_predictor,
    solve_with_model,
)
from .masked_decode import (
    MaskedDecodeConfig,
    MaskedProposalBatch,
    PartialDecodeResult,
    build_residual_candidate_mask,
    decode_partial_batch,
    sample_masked_proposals,
    solve_with_masked_model,
)
from .sequential_decode import (
    SequentialDecodeConfig,
    SequentialDecodeResult,
    SequentialProposalBatch,
    decode_sequential_batch,
    sample_sequential_proposals,
    solve_with_sequential_model,
)

__all__ = [
    "ConstructiveFallbackConfig",
    "ConstructiveFallbackResult",
    "GreedyLocalResult",
    "InferenceConfig",
    "LatencyAwareHeuristicCandidate",
    "LatencyAwareHeuristicResult",
    "LocalSearchConfig",
    "LocalSearchResult",
    "MaskedDecodeConfig",
    "MaskedProposalBatch",
    "PartialDecodeResult",
    "ProposalRecoveryConfig",
    "ProposalRecoveryResult",
    "RepairConfig",
    "RepairMove",
    "RepairResult",
    "SequentialDecodeConfig",
    "SequentialDecodeResult",
    "SequentialProposalBatch",
    "SolveResult",
    "TrajectoryCandidateSet",
    "TrajectoryDiagnosticConfig",
    "TrajectoryProposalBatch",
    "ViolationScore",
    "build_trajectory_candidate_set",
    "build_residual_candidate_mask",
    "construct_feasible_placement",
    "construct_greedy_local_placement",
    "construct_latency_aware_heuristic_candidates",
    "construct_latency_aware_heuristic_placement",
    "diagnose_reverse_trajectory",
    "decode_partial_batch",
    "decode_sequential_batch",
    "repair_placement",
    "recover_from_proposal",
    "run_local_search",
    "sample_direct_proposals",
    "sample_random_proposals",
    "sample_masked_proposals",
    "sample_reverse_proposals",
    "sample_reverse_trajectory_proposals",
    "sample_sequential_proposals",
    "solve_fallback_only",
    "solve_from_proposals",
    "solve_greedy_local",
    "solve_latency_aware_heuristic",
    "solve_local_search",
    "solve_milp_time_limit",
    "solve_with_direct_predictor",
    "solve_with_model",
    "solve_with_masked_model",
    "solve_with_sequential_model",
    "violation_score",
]
